In [1]:
import pandas as pd
import os
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

In [5]:
url = URL.create(
    drivername="mysql+mysqldb",
    username="root",
    password=os.getenv("MYSQL_PASSWORD"),
    host="127.0.0.1",
    port=3306,
    database="section_b"
)

engine = create_engine(url)

In [6]:
df = pd.read_csv(r"C:\Users\allex\Downloads\Sample - Superstore.csv", encoding="latin1")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df = df[['Order ID','Order Date','Sales','Quantity','Discount','Profit']]
df.head()

         Order ID  Order Date     Sales  Quantity  Discount    Profit
0  CA-2016-152156   11/8/2016  261.9600         2      0.00   41.9136
1  CA-2016-152156   11/8/2016  731.9400         3      0.00  219.5820
2  CA-2016-138688   6/12/2016   14.6200         2      0.00    6.8714
3  US-2015-108966  10/11/2015  957.5775         5      0.45 -383.0310
4  US-2015-108966  10/11/2015   22.3680         2      0.20    2.5164

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order ID    9994 non-null   str
 1   Order Date  9994 non-null   str
 2   Sales       9994 non-null   float64
 3   Quantity    9994 non-null   int64
 4   Discount    9994 non-null   float64
 5   Profit      9994 non-null   float64
dtypes: float64(3), int64(1), str(2)
memory usage: 693.7 KB

In [9]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order ID    9994 non-null   str
 1   Order Date  9994 non-null   datetime64[us]
 2   Sales       9994 non-null   float64
 3   Quantity    9994 non-null   int64
 4   Discount    9994 non-null   float64
 5   Profit      9994 non-null   float64
dtypes: datetime64[us](1), float64(3), int64(1), str(1)
memory usage: 605.2 KB

In [21]:
df.to_sql('orders',con=engine,if_exists='replace',index= False, method='multi', chunksize=5000)

9994

In [11]:
# Export to CSV without index column
df.to_csv('orders.csv', index=False)